from dotenv import load_dotenv
from typing import List
from pydantic import BaseModel, Field

load_dotenv()
from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from langchain_ollama import ChatOllama
from langchain_tavily import TavilySearch

class Source(BaseModel):
    """
    Schema for a source used by the agent
    """
    url:str = Field(description="The URL of the source")

class AgentResponse(BaseModel):
    """
    Schema for the agent response with answer and sources
    """
    answer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(default_factory=list, description="The list of sources used by the agent")

#llm = ChatOllama(model="gpt-oss:20b")
#llm = ChatOllama(model="llama2:latest")
#llm = ChatOllama(model="llama3:latest")
llm = ChatOllama(model="qwen2.5:latest")
tools = [TavilySearch()]
agent = create_agent(model=llm, tools=tools, response_format=AgentResponse)


def main():
    print("Hello from langchain-course!")
    result = agent.invoke(
        {
            "messages": HumanMessage(
                content="search for today's weather in Dublin"
            )
        }
    )
    print(result)


if __name__ == "__main__":
    main()
